### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by mbaertschi** [mbaertschi/DIVAServices-Spotlight#68]
There is still the question whether we should allow parallel processing or not? Right now, only one algorithm at one time is executed. From the frontside point of view, we have the possibility to allow parallel processing (e.g. three at the same time). @lunactic what you think about that?

**Comment by lunactic** [comment]
Is it possible to make a small frontend experiment to see if parallel execution would just be possible? Cause we just tried something here and it seems, that it should be possible out of the box.

**Comment by mbaertschi** [comment]
I will do it tomorrow ok?

**Comment by lunactic** [comment]
Sure! No hurry :)

**Comment by mbaertschi** [comment]
Tested and it works (right now parallel processing is activated -> da72621a468e05c15ccd741005c553d47f864fd3)

**Comment by mbaertschi** [comment]
I think we can close this issue. Reopen otherwise :-)
