### ISSUE TITLE
Possibility for output images directly be added to the images

### ISSUE THREAD

**Issue by lunactic** [mbaertschi/DIVAServices-Spotlight#71]
Would it be easily possible to add some kind of button to save a resulting output image to the uploaded images? (without the information that was drawn onto it.)

@mbaertschi If you feel it would take too much time just set the status to wontimplement and then I'll implement it sometimes in the future.

**Comment by mbaertschi** [comment]
I will add this feature! This will be the first step to allow chaining processes

**Comment by mbaertschi** [comment]
Actually I think it would be better to automatically add the image if there is one sent from DivaServices (server side) without the button. @lunactic do you agree on that?

**Comment by lunactic** [comment]
Yeah do it like this for now. Then I can change the behaviour easily later
