### ISSUE TITLE
[MINOR]: Zooming using scrollling

### ISSUE THREAD

**Issue by lunactic** [mbaertschi/DIVAServices-Spotlight#74]
Actually not really a bug, but there is also no better label ;-)

Can you maybe check if there is a possibility to use zoom in/out using the scroll direction as defined on the local computer?
Because right now zooming works like one would expect using a modern MacBook ;-)

**Comment by mbaertschi** [comment]
Bug???? Are you kidding me? :D
I can, but only if we change the label to downgrade instead of bug :-)

**Comment by lunactic** [comment]
Whatever works best for you ;-)

**Comment by lunactic** [comment]
Doesn't seem to be fixed for me :open_mouth: 

Draggin feels really weird now, and zooming only flips the image upside down.

Do you have a Windows VM and a mouse with which you could test it?

**Comment by mbaertschi** [comment]
OOps :-) I hope this time it works as expected
