### ISSUE TITLE
[Minor]: Create paths with integer pixel values

### ISSUE THREAD

**Issue by lunactic** [mbaertschi/DIVAServices-Spotlight#85]
Could you change the path creation in a way that it only sends integer pixel values to the backend? Or do you think it actually should be handled on the backend?

**Comment by mbaertschi** [comment]
Well, it depends on whether there are situations where float values are valid or not. If you always need integer values, then I can convert them on my backend (but we loose some precision in that case). If there are some algorithms which can handle float values, then I recommend that conversion is done on your backend (and only for those algorithms that require integer values).

**Comment by mbaertschi** [comment]
implemented in 149c34a92788db485801a18617a2d2cf5acc4dcf
